### ISSUE TITLE
Using zod-stream with functions/tools

### ISSUE THREAD

**Issue by lvegerano** [hack-dance/island-ai#36]
Is it possible to use this package with function calling. If you do you have an example? I could not find a way to pass multiple schemas and the module wont take in a ZodUnion. 

Thanks

**Comment by roodboi** [comment]
with what package?

zod-stream exposes a "withResponseModel" utility that maps the zod schema to the corresponding json schema

```
    const completionParams = withResponseModel({
      params: {
        ...client completion params,
        stream: false
      },
      mode: "TOOLS",
      response_model: { name: "", schema: z.object({ type: z.enum(["1", "2"]), details: z.discriminatedUnion("type", [z.object({ type: "1", other: z.string() }), z.object({ type: "1", other: z.string() })]) })}
    })
```

currently we don't explicitly support unions - we need an explicit type - but you could use a disciminated and switch based on some other type
