### ISSUE TITLE
zod dependency mismatch between GitHub and npmjs

### ISSUE THREAD

**Issue by matildepark** [hack-dance/island-ai#70]
On npm, schema-stream is [pinned to 3.22.4](https://www.npmjs.com/package/schema-stream?activeTab=code), whereas on GitHub, [it's ^3.23.3](https://github.com/hack-dance/island-ai/blob/37d59bcc90facf28806a48d592b1bbe4a09d7740/public-packages/schemaStream/package.json#L41), producing peer dependency errors.

**Comment by matildepark** [comment]
Appears to be [because you version after the fact](https://github.com/hack-dance/island-ai/issues/62), and so GitHub's code is actually 3.2.0's code, but unversioned for the new one.

**Comment by roodboi** [comment]
sorry for the delay - just merged it in :)
